"""initial schema

Revision ID: 75ff023e5522
Revises: 
Create Date: 2026-07-28 10:49:40.959265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ff023e5522'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('phase', sa.Enum('UPLOADED', 'VALIDATING', 'CONVERTING', 'SEPARATING', 'TRANSCRIBING', 'DETECTING_CHORDS', 'SMOOTHING', 'SYNCING', 'DONE', 'ERROR', name='songphase', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=8), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('capo', sa.Integer(), nullable=False),
    sa.Column('transpose_semitones', sa.Integer(), nullable=False),
    sa.Column('lyrics', sa.JSON(), nullable=False),
    sa.Column('chords', sa.JSON(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    op.drop_table('songs')
    # ### end Alembic commands ###
